---
services:
  # database (back-end)
  mysql-service:
    image: mysql:5.7
    volumes:
      - ~/mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    restart: always
    env_file: variables-mysql-service.env
    ports:
      - "3600:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-pwebapppw"]
      timeout: 20s
      retries: 10

  # web application (front-end)
  webapp:
    image: dyvantage01/webapp:version-1.0.8
    env_file: variables-webapp.env
    build: .
    ports:
      - "3000:80"
    depends_on:
      mysql-service:
        condition: service_healthy
