version: "0.1"
mysqldb:
    image: mysql:5.7
    #volumes:
    #  - ./mysql-data:/var/lib/mysql
    #  - ./mysql-init-files:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: root
      MYSQL_PASSWORD: wepapppw
      MYSQL_ROOT_PASSWORD: webapppw
    ports:
      - "3600:3306"
    #healthcheck:
    #  test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #  timeout: 20s
    #  retries: 10
